### ISSUE TITLE
rsuID needs verification

### ISSUE THREAD

**Issue by sacredartr** [open-v2x/edgeview#39]
## Describe the bug

rsuID need verification

## Screenshots
<img width="1679" alt="WechatIMG1159" src="https://user-images.githubusercontent.com/56632872/185531442-cd982210-8c57-4961-a472-5312aee9e06b.png">

## Desktop (please complete the following information):

- OS: mac
- Browser: chrome
- Version: master

**Comment by AriaAto** [comment]
the is RsuEsn rather than the rsuID
